### ISSUE TITLE
code bug

### ISSUE THREAD

**Issue by Jiawei0o0** [wofmanaf/Group-CAM#1]
I got some confusion about the code in main.py line 315.`images = images * saliency_maps + blur(images) + (1-saliency_maps)`. 
What do you mean to plus the (1 - saliency_maps) here? And what's the size of the saliency_maps here?

**Comment by VoooWei** [comment]
what the size of image and saliency_maps

**Comment by wofmanaf** [comment]
The saliency_maps have the same resolution as the images. If the image size is (1, 3, 224, 224), then the size of saliency maps should be (1, 1, 224, 224). The plus operation can ease the adversary effect (sharp edges, etc.) by the change of input pixel values.

**Comment by Jiawei0o0** [comment]
Thanks for your reply.
