### ISSUE TITLE
Using GroupCAM, get a NoneType

### ISSUE THREAD

**Issue by 1zeryu** [wofmanaf/Group-CAM#10]
I use your groupcam code, but I get the NoneType

![image](https://user-images.githubusercontent.com/90625606/196968688-e1f5653b-4154-451b-9fb7-e932f06e7e23.png)

Here is my code: 
```
def cam(model, loader, target_layer='conv1'):
    gc = GroupCAM(model, target_layer=target_layer)
    for i, (data, target) in enumerate(loader):
        if torch.cuda.is_available():
            data = data.cuda(non_blocking=True)
            target = target.cuda(non_blocking=True)
        saliency_maps = []
        model.eval()
        for idx in range(data.shape[0]):
            image = data[idx].unsqueeze(0)
            if idx == data.shape[0] - 1:
                saliency = gc(image, class_idx=target[idx], retain_graph=False)
            else:
                saliency = gc(image, class_idx=target[idx], retain_graph=True)
            saliency = saliency.to(device)
            saliency_maps.append(saliency)
        saliency_maps = torch.cat(saliency_maps, dim=0)
        mean = torch.mean(saliency_maps)
        saliency_maps = torch.where(saliency_maps < mean, 0.0, 1.0)
```

The model is my DNN, and the loader is the CIFAR-10 eval_loader, 

My PyTorch version: '1.12.1+cu116'
Python version: 3.7

**Comment by wofmanaf** [comment]
This could be target_layer not found. You can print the model to check whether target_layer 'conv1' exists.

**Comment by 1zeryu** [comment]
I have checked it, the target-layer is right. And I found that score_saliency_map gets nan in groupcam in the CIFAR-10 dataset.

**Comment by chenrxi** [comment]
have you solved it？I also found that score_saliency_map gets nan in groupcam in the CIFAR10/100 dataset
 @1zeryu

**Comment by 1zeryu** [comment]
No, I didn't solve it, and finally, I choose to use torchcam to implement my experiments.
